version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "App/app.py"]
    ports:
      - "5678:5678"

  node-app:
    image: node:18
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    ports:
      - "9229:9229"
